### ISSUE TITLE
React error in console

### ISSUE THREAD

**Issue by pranavbharadwaj007** [pranavbharadwaj007/Live-Vaccine-Slot#1]
![error](https://user-images.githubusercontent.com/55646472/116966081-fd6cbd80-accc-11eb-862e-5e509a02131f.PNG)

**Comment by dhanushkamathS** [comment]
Hey, nice project,
You have passed gutterBottom prop in slot.js which might be causing this error.
i would like to contribute to your project
![Screenshot from 2021-05-09 00-12-21](https://user-images.githubusercontent.com/47971198/117549996-4620cf80-b05b-11eb-93b1-dcc5b4547f9c.png)

**Comment by pranavbharadwaj007** [comment]
sure
just make a PR if ur confident

**Comment by pranavbharadwaj007** [comment]
@dhanushkamathS lets connect via LinkedIn  https://www.linkedin.com/in/pranavbharadwaj007/
